### ISSUE TITLE
让潜在的错误[curl related]，暴露在用户面前的建议

### ISSUE THREAD

**Issue by dacheng-gao** [lokielse/omnipay-unionpay#12]
嗨，@lokielse ，你好。

关于 issue #11 ，排查过程有些艰难，(maybe just for my only)，因此，如果在以下文件：

```
omnipay-unionpay/src/Helper.php
```

里的 `sendHttpRequest` 方法中，添加以下代码行：

```
if (curl_error($ch)) {
    throw new \RuntimeException(curl_error($ch));
}
```

因为，curl如果发生错误，只会返回false结果，用户层不知在哪里返回的false，唯有沿着代码调用栈层层往上debug。

没有v0.3.8的分支，v0.4.x也不再使用这个方法，因此我不知道怎么发PR。

**Comment by lokielse** [comment]
@darrengaogao 好的，感谢提醒，已在`v0.3.10`版本中加入。
