### ISSUE TITLE
请问现在的无跳转支付的开发进度是怎样的？

### ISSUE THREAD

**Issue by fasthold** [lokielse/omnipay-unionpay#20]
作者好！我这边最近急需使用无跳转支付，在readme里看是显示的 alpha 状态， 想知道现在这个支付方式的可用性怎样？谢谢！

**Comment by lokielse** [comment]
你好，无跳转支付是刚实现的网关，写了些测试，暂未在生成环境使用过!!!  可能存在在支付流程方面不完善的问题。

你可以自行看一下以下文件以及关联的Request和Response。

https://github.com/lokielse/omnipay-unionpay/blob/76f4bfa0ceb95debba94d04e7885818d29ea0195/src/WtzGateway.php#L100

使用过程中有问题欢迎提issue或PR
