### ISSUE TITLE
PHP版本要求最少需要7.1版本吧？

### ISSUE THREAD

**Issue by rootrl** [lokielse/omnipay-unionpay#25]
我看readme中说for PHP 5.3+，但是该项目引用了guzzle，和symfony的http-foundation，都是要求7.1以上，不然跑不起来。。

**Comment by lokielse** [comment]
是的，需要`php 7.1`

**Comment by rootrl** [comment]
嗯 我的环境是5.4好像 刚把guzzle和symfony改了个遍 终于跑通了。。
感觉应该加个说明啊 便于开发者选择
