### ISSUE TITLE
异步通知签名验证成功，同步通知签名验证失败

### ISSUE THREAD

**Issue by beyonddevil** [lokielse/omnipay-unionpay#27]
测试时，同步通知和异步通知，都返回 respCode = 00，但是经过 Singer->verifyWithRSA() 验证签名时，同步失败！！异步成功！！导致同步的 verify_success = false，is_paid() 调用返回失败！

大家有没有遇到类似的问题！

**Comment by lokielse** [comment]
```
$response = $gateway->completePurchase(['request_params'=>$_REQUEST])->send();
```

这里勿使用`$_REQUEST`，因为其包含的信息不纯粹。
建议换成`$_GET`, `$_POST` 或者 `array_merge($_GET, $_POST)`

**Comment by beyonddevil** [comment]
_POST 可以，谢谢

**Comment by beyonddevil** [comment]
老大，再问个问题，咱们这个目前不知道 5.0.1 版本，是吗

**Comment by lokielse** [comment]
好的，感谢提醒，我关注一下官方的SDK进展。

**Comment by beyonddevil** [comment]
打错了，我说的是，目前不支持 5.0.1 版本...，非常感谢😁l

**Comment by lokielse** [comment]
OK.
