### ISSUE TITLE
网关支付成功返回报错 Can not find certId in folder *

### ISSUE THREAD

**Issue by Aexus** [lokielse/omnipay-unionpay#29]
使用最新版本的omnipay-unionpay.银联网关开发版本试了都不行.麻烦有空回复下,谢谢!

**Comment by Aexus** [comment]
需要引入verify_sign_acp.cer,已解决!

**Comment by GabbyMrH** [comment]
> 需要引入verify_sign_acp.cer,已解决!

你好，请问这个文件在哪里下载呀？是哪个包呢?
